### ISSUE TITLE
Правки по коду

### ISSUE THREAD

**Issue by nikolai-shabalin** [alex-koshara/lection-html#1]
`<meta http-equiv="X-UA-Compatible" content="IE=edge">` можно удалять. Мы уже это не используем

Атрибут `class` всегда должен быть первым атрибутом у тега, то есть у `a href="#" class="main-nav__link">Каталог</a>` надо перенести `class`

Давайте в `<nav class="page-header__main-nav main-nav">` всё-таки добавим список `<ul>`

Для `<img src="" alt="Логотип" class="logo__img">` нужно добавить атрибуты `width` и `height` без единиц измерения `px`. И для остальных картинок тоже самое

В 46 строке `<span class="promo__price">22 000 <svg` перенести тег `<svg>` на новую строку, а то криво выглядит

В 55 строке `<seciton class="popular container">` - `seciton` заменить на `section`

Дивы-контейнеры, которые центруют я бы не добавлял на этой теме. Тут всё-таки про семантику. Центрирование это уже про стилизацию. То есть вначале мы описываем данные с помощью семантических тегов, а потом занимаемся стилизаций: расположение, цвета, размеры.

Социальные сети тоже давайте обернём в список `<ul>` и в "О компании", "Оплата и доставка" тоже. Это однородные данные поэтому есть смысл добавить им смысла.

В остальном всё очень круто. Очень понравилось именование. Сразу понятно, не смотря на макет, что имеется ввиду.

**Comment by alex-koshara** [comment]
@nikolai-shabalin привязал ПР с правками
